language: java
jdk: openjdk11
os: linux
dist: xenial

before_install:
  - wget https://services.gradle.org/distributions/gradle-6.6-bin.zip
  - unzip -qq gradle-6.6-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.6
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

install: gradle wrapper --gradle-version 6.6
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/